export const data = [
  {
    ID: 1,
    Name: 'Unauthorized Access Attempt',
    Description: 'Multiple failed login attempts detected from a single IP address.',
    Severity: 'Medium',
    Time: 1674038400,
  },
  {
    ID: 2,
    Name: 'Malware Detected',
    Description: 'Antivirus software detected and quarantined a Trojan horse.',
    Severity: 'High',
    Time: 1674042000,
  },
  {
    ID: 3,
    Name: 'Phishing Email Reported',
    Description: 'User reported a phishing email attempting to acquire login credentials.',
    Severity: 'Low',
    Time: 1674045600,
  },
  {
    ID: 4,
    Name: 'Data Leakage',
    Description: 'Sensitive data found in an unauthorized location.',
    Severity: 'High',
    Time: 1674049200,
  },
  {
    ID: 5,
    Name: 'Network Traffic Anomaly',
    Description: 'Unusual outbound traffic pattern detected, possible exfiltration attempt.',
    Severity: 'Medium',
    Time: 1674052800,
  },
  {
    ID: 6,
    Name: 'Suspicious File Execution',
    Description: 'Execution of an unrecognized and potentially harmful executable detected.',
    Severity: 'Medium',
    Time: 1674056400,
  },
  {
    ID: 7,
    Name: 'External Penetration Test Alert',
    Description: 'Alerts triggered by an authorized external penetration test.',
    Severity: 'Low',
    Time: 1674060000,
  },
  {
    ID: 8,
    Name: 'Internal Compliance Violation',
    Description: 'Employee accessed restricted data violating internal compliance protocols.',
    Severity: 'High',
    Time: 1674063600,
  },
  {
    ID: 9,
    Name: 'DDoS Attack Detected',
    Description: 'Distributed Denial of Service attack identified targeting the main server.',
    Severity: 'High',
    Time: 1674067200,
  },
  {
    ID: 10,
    Name: 'Irregular Admin Activity',
    Description: 'Unusual activity detected in administrator account outside normal hours.',
    Severity: 'Medium',
    Time: 1674070800,
  },
  {
    ID: 11,
    Name: 'Firewall Breach Attempt',
    Description: 'Repeated attempts to bypass firewall detected from an external source.',
    Severity: 'Medium',
    Time: 1674074400,
  },
  {
    ID: 12,
    Name: 'Insecure Password Usage',
    Description: 'User account using a password that does not meet security standards.',
    Severity: 'Low',
    Time: 1674078000,
  },
  {
    ID: 13,
    Name: 'Unexpected Data Export',
    Description: 'Large data export detected which is not in line with normal user behavior.',
    Severity: 'High',
    Time: 1674081600,
  },
  {
    ID: 14,
    Name: 'Suspicious Login from Unusual Location',
    Description: 'Login to a sensitive system detected from a geographically unusual location.',
    Severity: 'Medium',
    Time: 1674085200,
  },
  {
    ID: 15,
    Name: 'Encryption Key Mismanagement',
    Description: 'Encryption keys found stored in an insecure manner.',
    Severity: 'High',
    Time: 1674088800,
  },
  {
    ID: 16,
    Name: 'Excessive User Privileges',
    Description: 'User account detected with more privileges than required for its role.',
    Severity: 'Medium',
    Time: 1674092400,
  },
  {
    ID: 17,
    Name: 'Unauthorized Software Installation',
    Description: 'Installation of unapproved software detected on a company device.',
    Severity: 'Medium',
    Time: 1674096000,
  },
  {
    ID: 18,
    Name: 'Suspicious Network Scanning Activity',
    Description: 'Network scanning activity detected, indicating a potential reconnaissance by an attacker.',
    Severity: 'High',
    Time: 1674099600,
  },
  {
    ID: 19,
    Name: 'Data Integrity Alert',
    Description: 'Inconsistencies found in database suggesting possible data tampering.',
    Severity: 'High',
    Time: 1674103200,
  },
  {
    ID: 20,
    Name: 'Anomalous User Behavior',
    Description: 'Behavioral analytics flagged unusual activity in a normally low-activity user account.',
    Severity: 'Medium',
    Time: 1674106800,
  },
];
